version: '3.7'

services:

  bookstore-ui:
    container_name: bookstore-ui
    build:
      context: ./bookstore-ui
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  bookstore-books:
    container_name: bookstore-books
    build:
        context: ./bookstore-books
        dockerfile: Dockerfile
    ports:
        - 8080:8080
