version: '3.7'

services:

  bookstore-ui:
    container_name: bookstore-ui
    build:
      context: ./bookstore-ui
      dockerfile: Dockerfile
    ports:
      - 3001:3000

  bookstore-books:
    container_name: bookstore-books
    build:
        context: ./bookstore-books
        dockerfile: Dockerfile
    ports:
        - 8080:8080
