swagger: "2.0"
consumes:
- application/json
info:
  title: bookstore-books
  description: A microservice for storing information of books
  version: 1.0.0
paths: 
  /books:
    get:
      tags:
        - books
      responses:
        200:
          description: list the books
          schema:
            type: array
            items:
              $ref: "#/definitions/book"
        default:
          description: generic error response
          schema:
              $ref: "#/definitions/error"
  /book/{id}/image:
    get:
      tags:
        - book-image
      parameters:
        - name: id
          in: path
          type: string
          required: true
      produces:
        - image/png
        - image/gif
        - image/jpeg
      responses:
        200:
          description: show image of a book
          schema:
            type: file
        404:
          description: id not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: generic error response
          schema:
              $ref: "#/definitions/error"
  
 
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  book:
    type: object
    required:
      - id
      - title
      - author
      - price
    properties:
      id:
        type: string
      title:
        type: string
      author:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string